# Generated by Django 4.2.18 on 2025-01-20 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'AKINCI'), ('KIZILELMA', 'KIZILELMA')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('WING', 'Kanat Takımı'), ('BODY', 'Gövde Takımı'), ('TAIL', 'Kuyruk Takımı'), ('AVIONICS', 'Aviyonik Takımı'), ('ASSEMBLY', 'Montaj Takımı')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WING', 'Kanat'), ('BODY', 'Gövde'), ('TAIL', 'Kuyruk'), ('AVIONICS', 'Aviyonik')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.aircrafttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembled_at', models.DateTimeField(auto_now_add=True)),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.aircrafttype')),
                ('assembled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.personnel')),
                ('avionics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_avionics', to='production.part')),
                ('body', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_body', to='production.part')),
                ('tail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_tail', to='production.part')),
                ('wing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_wing', to='production.part')),
            ],
        ),
    ]
